-- 코드를 입력하세요 
SELECT DISTINCT(A.CAR_ID) 
FROM CAR_RENTAL_COMPANY_CAR A 
 INNER JOIN 
 CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
ON A.CAR_ID = B.CAR_ID
WHERE 1=1
 AND A.CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR 
                 WHERE CAR_TYPE = '세단'
                AND TO_CHAR(EXTRACT(MONTH FROM START_DATE)) = 10)

 ORDER BY A.CAR_ID DESC

 -- EXISTS를 사용한 버전.
 SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR A
WHERE EXISTS (SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
             WHERE 1=1 
              AND A.CAR_ID = B.CAR_ID
             AND TO_CHAR(EXTRACT(MONTH FROM START_DATE)) = 10)
AND A.CAR_TYPE='세단'
ORDER BY CAR_ID DESC